
services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: inception-mariadb
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - network
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: inception-wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    volumes:
      - wp-files:/var/www/wordpress
    networks:
      - network
    restart: unless-stopped

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: inception-nginx
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp-files:/var/www/wordpress
    networks:
      - network
    restart: unless-stopped

  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: inception-redis
    volumes:
      - rd-data:/data
    ports:
      - "6379"
    networks:
      - network
    restart: unless-stopped

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    container_name: inception-ftp
    depends_on:
      - wordpress
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    env_file:
      - .env
    volumes:
      - wp-files:/var/www/wordpress
    networks:
      - network
    restart: unless-stopped

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: inception-adminer
    ports:
      - "8081:8080"
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - network

  static_file:
    build: ./requirements/bonus/static_file
    image: static_file
    container_name: inception-static_file
    ports:
      - "122:80"
    networks:
      - network
    restart: unless-stopped

  portainer:
    build: ./requirements/bonus/portainer
    image: portainer
    container_name: inception-portainer
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - por-data:/data
    networks:
      - network
    restart: unless-stopped

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yaait-am/data/mariadb
  wp-files:
    driver: local
    driver_opts:
      type: none
      o: bind # so we can choose the path of the volumes
      device: /home/yaait-am/data/wordpress
  rd-data:
    driver: local
  por-data:
    driver: local

networks:
  network:
    driver: bridge # so can the container speek with other inside the network only by name
